"""naming update

Revision ID: 963eb97caf14
Revises: 75f84f2ee939
Create Date: 2024-04-30 16:21:04.342995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963eb97caf14'
down_revision = '75f84f2ee939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mottos',
    sa.Column('motto_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('motto_id')
    )
    op.drop_table('motto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motto',
    sa.Column('motto_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('motto', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('motto_id')
    )
    op.drop_table('mottos')
    # ### end Alembic commands ###
