"""naming update

Revision ID: be54be751096
Revises: 963eb97caf14
Create Date: 2024-04-30 16:23:42.596911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be54be751096'
down_revision = '963eb97caf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mottos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto_text', sa.Text(), nullable=False))
        batch_op.drop_column('motto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mottos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto', sa.TEXT(), nullable=False))
        batch_op.drop_column('motto_text')

    # ### end Alembic commands ###
